//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace ClientForm.LopHocPhanDKWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LopHocPhanDKWSSoap", Namespace="http://tempuri.org/")]
    public partial class LopHocPhanDKWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getLopHocPhanDKByMasvOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LopHocPhanDKWS() {
            this.Url = global::ClientForm.Properties.Settings.Default.ClientForm_LopHocPhanDKWS_LopHocPhanDKWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getLopHocPhanDKByMasvCompletedEventHandler getLopHocPhanDKByMasvCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLopHocPhanDKByMasv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LopHocPhanDKWSI getLopHocPhanDKByMasv(string masv) {
            object[] results = this.Invoke("getLopHocPhanDKByMasv", new object[] {
                        masv});
            return ((LopHocPhanDKWSI)(results[0]));
        }
        
        /// <remarks/>
        public void getLopHocPhanDKByMasvAsync(string masv) {
            this.getLopHocPhanDKByMasvAsync(masv, null);
        }
        
        /// <remarks/>
        public void getLopHocPhanDKByMasvAsync(string masv, object userState) {
            if ((this.getLopHocPhanDKByMasvOperationCompleted == null)) {
                this.getLopHocPhanDKByMasvOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLopHocPhanDKByMasvOperationCompleted);
            }
            this.InvokeAsync("getLopHocPhanDKByMasv", new object[] {
                        masv}, this.getLopHocPhanDKByMasvOperationCompleted, userState);
        }
        
        private void OngetLopHocPhanDKByMasvOperationCompleted(object arg) {
            if ((this.getLopHocPhanDKByMasvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLopHocPhanDKByMasvCompleted(this, new getLopHocPhanDKByMasvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopHocPhanDKWSI {
        
        private LopHocPhan[] lopHocPhansField;
        
        private HocPhan[] hocPhansField;
        
        private ChiTietLopHocPhan[] chiTietLopHocPhansField;
        
        private CanBoGiaoVien[] canBoGiaoViensField;
        
        private HocKy[] hocKysField;
        
        /// <remarks/>
        public LopHocPhan[] LopHocPhans {
            get {
                return this.lopHocPhansField;
            }
            set {
                this.lopHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public HocPhan[] HocPhans {
            get {
                return this.hocPhansField;
            }
            set {
                this.hocPhansField = value;
            }
        }
        
        /// <remarks/>
        public ChiTietLopHocPhan[] ChiTietLopHocPhans {
            get {
                return this.chiTietLopHocPhansField;
            }
            set {
                this.chiTietLopHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public CanBoGiaoVien[] CanBoGiaoViens {
            get {
                return this.canBoGiaoViensField;
            }
            set {
                this.canBoGiaoViensField = value;
            }
        }
        
        /// <remarks/>
        public HocKy[] HocKys {
            get {
                return this.hocKysField;
            }
            set {
                this.hocKysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopHocPhan {
        
        private string malhpField;
        
        private string mahpField;
        
        private string macbgvField;
        
        private string mahkField;
        
        private System.Nullable<int> soluongField;
        
        private System.Nullable<int> soluongdkField;
        
        private System.Nullable<System.DateTime> ngaybatdauField;
        
        private System.Nullable<System.DateTime> ngaythiField;
        
        private string giothiField;
        
        private System.Nullable<System.DateTime> ngaynopdiemField;
        
        private string ghichuField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private ChiTietLopHocPhan[] chiTietLopHocPhansField;
        
        private LopHocPhanSinhVien[] lopHocPhanSinhViensField;
        
        private NhatKy[] nhatKiesField;
        
        private PhongThi[] phongThisField;
        
        private CanBoGiaoVien canBoGiaoVienField;
        
        private HocKy hocKyField;
        
        private HocPhan hocPhanField;
        
        /// <remarks/>
        public string Malhp {
            get {
                return this.malhpField;
            }
            set {
                this.malhpField = value;
            }
        }
        
        /// <remarks/>
        public string Mahp {
            get {
                return this.mahpField;
            }
            set {
                this.mahpField = value;
            }
        }
        
        /// <remarks/>
        public string Macbgv {
            get {
                return this.macbgvField;
            }
            set {
                this.macbgvField = value;
            }
        }
        
        /// <remarks/>
        public string Mahk {
            get {
                return this.mahkField;
            }
            set {
                this.mahkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Soluong {
            get {
                return this.soluongField;
            }
            set {
                this.soluongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Soluongdk {
            get {
                return this.soluongdkField;
            }
            set {
                this.soluongdkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Ngaybatdau {
            get {
                return this.ngaybatdauField;
            }
            set {
                this.ngaybatdauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Ngaythi {
            get {
                return this.ngaythiField;
            }
            set {
                this.ngaythiField = value;
            }
        }
        
        /// <remarks/>
        public string Giothi {
            get {
                return this.giothiField;
            }
            set {
                this.giothiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Ngaynopdiem {
            get {
                return this.ngaynopdiemField;
            }
            set {
                this.ngaynopdiemField = value;
            }
        }
        
        /// <remarks/>
        public string Ghichu {
            get {
                return this.ghichuField;
            }
            set {
                this.ghichuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public ChiTietLopHocPhan[] ChiTietLopHocPhans {
            get {
                return this.chiTietLopHocPhansField;
            }
            set {
                this.chiTietLopHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhanSinhVien[] LopHocPhanSinhViens {
            get {
                return this.lopHocPhanSinhViensField;
            }
            set {
                this.lopHocPhanSinhViensField = value;
            }
        }
        
        /// <remarks/>
        public NhatKy[] NhatKies {
            get {
                return this.nhatKiesField;
            }
            set {
                this.nhatKiesField = value;
            }
        }
        
        /// <remarks/>
        public PhongThi[] PhongThis {
            get {
                return this.phongThisField;
            }
            set {
                this.phongThisField = value;
            }
        }
        
        /// <remarks/>
        public CanBoGiaoVien CanBoGiaoVien {
            get {
                return this.canBoGiaoVienField;
            }
            set {
                this.canBoGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public HocKy HocKy {
            get {
                return this.hocKyField;
            }
            set {
                this.hocKyField = value;
            }
        }
        
        /// <remarks/>
        public HocPhan HocPhan {
            get {
                return this.hocPhanField;
            }
            set {
                this.hocPhanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChiTietLopHocPhan {
        
        private int idField;
        
        private string malhpField;
        
        private System.Nullable<int> thuField;
        
        private System.Nullable<int> tutietField;
        
        private System.Nullable<int> dentietField;
        
        private string phongField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private LopHocPhan lopHocPhanField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Malhp {
            get {
                return this.malhpField;
            }
            set {
                this.malhpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Thu {
            get {
                return this.thuField;
            }
            set {
                this.thuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Tutiet {
            get {
                return this.tutietField;
            }
            set {
                this.tutietField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Dentiet {
            get {
                return this.dentietField;
            }
            set {
                this.dentietField = value;
            }
        }
        
        /// <remarks/>
        public string Phong {
            get {
                return this.phongField;
            }
            set {
                this.phongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhan LopHocPhan {
            get {
                return this.lopHocPhanField;
            }
            set {
                this.lopHocPhanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhongThi {
        
        private int idField;
        
        private string maphongField;
        
        private string malhpField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private LopHocPhan lopHocPhanField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Maphong {
            get {
                return this.maphongField;
            }
            set {
                this.maphongField = value;
            }
        }
        
        /// <remarks/>
        public string Malhp {
            get {
                return this.malhpField;
            }
            set {
                this.malhpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhan LopHocPhan {
            get {
                return this.lopHocPhanField;
            }
            set {
                this.lopHocPhanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhuHuynh {
        
        private int maphField;
        
        private string hotenchaField;
        
        private string nghenghiepchaField;
        
        private string hotenmeField;
        
        private string nghenghiepmeField;
        
        private string diachiField;
        
        private string sodienthoaiField;
        
        private string emailField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private SinhVien[] sinhViensField;
        
        /// <remarks/>
        public int Maph {
            get {
                return this.maphField;
            }
            set {
                this.maphField = value;
            }
        }
        
        /// <remarks/>
        public string Hotencha {
            get {
                return this.hotenchaField;
            }
            set {
                this.hotenchaField = value;
            }
        }
        
        /// <remarks/>
        public string Nghenghiepcha {
            get {
                return this.nghenghiepchaField;
            }
            set {
                this.nghenghiepchaField = value;
            }
        }
        
        /// <remarks/>
        public string Hotenme {
            get {
                return this.hotenmeField;
            }
            set {
                this.hotenmeField = value;
            }
        }
        
        /// <remarks/>
        public string Nghenghiepme {
            get {
                return this.nghenghiepmeField;
            }
            set {
                this.nghenghiepmeField = value;
            }
        }
        
        /// <remarks/>
        public string Diachi {
            get {
                return this.diachiField;
            }
            set {
                this.diachiField = value;
            }
        }
        
        /// <remarks/>
        public string Sodienthoai {
            get {
                return this.sodienthoaiField;
            }
            set {
                this.sodienthoaiField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public SinhVien[] SinhViens {
            get {
                return this.sinhViensField;
            }
            set {
                this.sinhViensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SinhVien {
        
        private string masvField;
        
        private System.Nullable<int> macsField;
        
        private System.Nullable<int> maphField;
        
        private string malshField;
        
        private string tensvField;
        
        private string sodtField;
        
        private string emailField;
        
        private System.Nullable<System.DateTime> ngaysinhField;
        
        private string noisinhField;
        
        private string noithuongtruField;
        
        private string gioitinhField;
        
        private string dantocField;
        
        private string tongiaoField;
        
        private string socmndField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private TinTucSinhVien[] tinTucSinhViensField;
        
        private LopHocPhanSinhVien[] lopHocPhanSinhViensField;
        
        private LopSinhHoatSinhVien[] lopSinhHoatSinhViensField;
        
        private TheoDoiHocKy[] theoDoiHocKiesField;
        
        private ChinhSach chinhSachField;
        
        private PhuHuynh phuHuynhField;
        
        private LopSinhHoat lopSinhHoatField;
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Macs {
            get {
                return this.macsField;
            }
            set {
                this.macsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Maph {
            get {
                return this.maphField;
            }
            set {
                this.maphField = value;
            }
        }
        
        /// <remarks/>
        public string Malsh {
            get {
                return this.malshField;
            }
            set {
                this.malshField = value;
            }
        }
        
        /// <remarks/>
        public string Tensv {
            get {
                return this.tensvField;
            }
            set {
                this.tensvField = value;
            }
        }
        
        /// <remarks/>
        public string Sodt {
            get {
                return this.sodtField;
            }
            set {
                this.sodtField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Ngaysinh {
            get {
                return this.ngaysinhField;
            }
            set {
                this.ngaysinhField = value;
            }
        }
        
        /// <remarks/>
        public string Noisinh {
            get {
                return this.noisinhField;
            }
            set {
                this.noisinhField = value;
            }
        }
        
        /// <remarks/>
        public string Noithuongtru {
            get {
                return this.noithuongtruField;
            }
            set {
                this.noithuongtruField = value;
            }
        }
        
        /// <remarks/>
        public string Gioitinh {
            get {
                return this.gioitinhField;
            }
            set {
                this.gioitinhField = value;
            }
        }
        
        /// <remarks/>
        public string Dantoc {
            get {
                return this.dantocField;
            }
            set {
                this.dantocField = value;
            }
        }
        
        /// <remarks/>
        public string Tongiao {
            get {
                return this.tongiaoField;
            }
            set {
                this.tongiaoField = value;
            }
        }
        
        /// <remarks/>
        public string Socmnd {
            get {
                return this.socmndField;
            }
            set {
                this.socmndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public TinTucSinhVien[] TinTucSinhViens {
            get {
                return this.tinTucSinhViensField;
            }
            set {
                this.tinTucSinhViensField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhanSinhVien[] LopHocPhanSinhViens {
            get {
                return this.lopHocPhanSinhViensField;
            }
            set {
                this.lopHocPhanSinhViensField = value;
            }
        }
        
        /// <remarks/>
        public LopSinhHoatSinhVien[] LopSinhHoatSinhViens {
            get {
                return this.lopSinhHoatSinhViensField;
            }
            set {
                this.lopSinhHoatSinhViensField = value;
            }
        }
        
        /// <remarks/>
        public TheoDoiHocKy[] TheoDoiHocKies {
            get {
                return this.theoDoiHocKiesField;
            }
            set {
                this.theoDoiHocKiesField = value;
            }
        }
        
        /// <remarks/>
        public ChinhSach ChinhSach {
            get {
                return this.chinhSachField;
            }
            set {
                this.chinhSachField = value;
            }
        }
        
        /// <remarks/>
        public PhuHuynh PhuHuynh {
            get {
                return this.phuHuynhField;
            }
            set {
                this.phuHuynhField = value;
            }
        }
        
        /// <remarks/>
        public LopSinhHoat LopSinhHoat {
            get {
                return this.lopSinhHoatField;
            }
            set {
                this.lopSinhHoatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TinTucSinhVien {
        
        private int idField;
        
        private string masvField;
        
        private string tieudeField;
        
        private string tomtatField;
        
        private string noidungField;
        
        private string filedinhkemField;
        
        private System.Nullable<System.DateTime> thoigianField;
        
        private string hinhanhField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private SinhVien sinhVienField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        public string Tieude {
            get {
                return this.tieudeField;
            }
            set {
                this.tieudeField = value;
            }
        }
        
        /// <remarks/>
        public string Tomtat {
            get {
                return this.tomtatField;
            }
            set {
                this.tomtatField = value;
            }
        }
        
        /// <remarks/>
        public string Noidung {
            get {
                return this.noidungField;
            }
            set {
                this.noidungField = value;
            }
        }
        
        /// <remarks/>
        public string Filedinhkem {
            get {
                return this.filedinhkemField;
            }
            set {
                this.filedinhkemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Thoigian {
            get {
                return this.thoigianField;
            }
            set {
                this.thoigianField = value;
            }
        }
        
        /// <remarks/>
        public string Hinhanh {
            get {
                return this.hinhanhField;
            }
            set {
                this.hinhanhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public SinhVien SinhVien {
            get {
                return this.sinhVienField;
            }
            set {
                this.sinhVienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopHocPhanSinhVien {
        
        private int idField;
        
        private string masvField;
        
        private string malhpField;
        
        private System.Nullable<double> dtkgkField;
        
        private System.Nullable<double> dtkckField;
        
        private System.Nullable<double> dtkhpField;
        
        private System.Nullable<double> dccField;
        
        private System.Nullable<bool> tichluyField;
        
        private string ghichuField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private LopHocPhan lopHocPhanField;
        
        private SinhVien sinhVienField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        public string Malhp {
            get {
                return this.malhpField;
            }
            set {
                this.malhpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dtkgk {
            get {
                return this.dtkgkField;
            }
            set {
                this.dtkgkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dtkck {
            get {
                return this.dtkckField;
            }
            set {
                this.dtkckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dtkhp {
            get {
                return this.dtkhpField;
            }
            set {
                this.dtkhpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dcc {
            get {
                return this.dccField;
            }
            set {
                this.dccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Tichluy {
            get {
                return this.tichluyField;
            }
            set {
                this.tichluyField = value;
            }
        }
        
        /// <remarks/>
        public string Ghichu {
            get {
                return this.ghichuField;
            }
            set {
                this.ghichuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhan LopHocPhan {
            get {
                return this.lopHocPhanField;
            }
            set {
                this.lopHocPhanField = value;
            }
        }
        
        /// <remarks/>
        public SinhVien SinhVien {
            get {
                return this.sinhVienField;
            }
            set {
                this.sinhVienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopSinhHoatSinhVien {
        
        private int idField;
        
        private string malshField;
        
        private string masvField;
        
        private System.Nullable<int> sotctlField;
        
        private System.Nullable<double> dtbctlField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private LopSinhHoat lopSinhHoatField;
        
        private SinhVien sinhVienField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Malsh {
            get {
                return this.malshField;
            }
            set {
                this.malshField = value;
            }
        }
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotctl {
            get {
                return this.sotctlField;
            }
            set {
                this.sotctlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dtbctl {
            get {
                return this.dtbctlField;
            }
            set {
                this.dtbctlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public LopSinhHoat LopSinhHoat {
            get {
                return this.lopSinhHoatField;
            }
            set {
                this.lopSinhHoatField = value;
            }
        }
        
        /// <remarks/>
        public SinhVien SinhVien {
            get {
                return this.sinhVienField;
            }
            set {
                this.sinhVienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopSinhHoat {
        
        private string malshField;
        
        private string manganhField;
        
        private string macbgvField;
        
        private string tenlshField;
        
        private System.Nullable<int> sisoField;
        
        private System.Nullable<int> khoaField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private LopSinhHoatSinhVien[] lopSinhHoatSinhViensField;
        
        private SinhVien[] sinhViensField;
        
        private CanBoGiaoVien canBoGiaoVienField;
        
        private Nganh nganhField;
        
        /// <remarks/>
        public string Malsh {
            get {
                return this.malshField;
            }
            set {
                this.malshField = value;
            }
        }
        
        /// <remarks/>
        public string Manganh {
            get {
                return this.manganhField;
            }
            set {
                this.manganhField = value;
            }
        }
        
        /// <remarks/>
        public string Macbgv {
            get {
                return this.macbgvField;
            }
            set {
                this.macbgvField = value;
            }
        }
        
        /// <remarks/>
        public string Tenlsh {
            get {
                return this.tenlshField;
            }
            set {
                this.tenlshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Siso {
            get {
                return this.sisoField;
            }
            set {
                this.sisoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Khoa {
            get {
                return this.khoaField;
            }
            set {
                this.khoaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public LopSinhHoatSinhVien[] LopSinhHoatSinhViens {
            get {
                return this.lopSinhHoatSinhViensField;
            }
            set {
                this.lopSinhHoatSinhViensField = value;
            }
        }
        
        /// <remarks/>
        public SinhVien[] SinhViens {
            get {
                return this.sinhViensField;
            }
            set {
                this.sinhViensField = value;
            }
        }
        
        /// <remarks/>
        public CanBoGiaoVien CanBoGiaoVien {
            get {
                return this.canBoGiaoVienField;
            }
            set {
                this.canBoGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public Nganh Nganh {
            get {
                return this.nganhField;
            }
            set {
                this.nganhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CanBoGiaoVien {
        
        private string macbgvField;
        
        private string tencbgvField;
        
        private string sodtField;
        
        private string emailField;
        
        private System.Nullable<System.DateTime> ngaysinhField;
        
        private string noisinhField;
        
        private string noithuongtruField;
        
        private string gioitinhField;
        
        private string dantocField;
        
        private string tongiaoField;
        
        private string socmndField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private LopHocPhan[] lopHocPhansField;
        
        private LopSinhHoat[] lopSinhHoatsField;
        
        private NhatKy[] nhatKiesField;
        
        private TinTucDaoTao[] tinTucDaoTaosField;
        
        /// <remarks/>
        public string Macbgv {
            get {
                return this.macbgvField;
            }
            set {
                this.macbgvField = value;
            }
        }
        
        /// <remarks/>
        public string Tencbgv {
            get {
                return this.tencbgvField;
            }
            set {
                this.tencbgvField = value;
            }
        }
        
        /// <remarks/>
        public string Sodt {
            get {
                return this.sodtField;
            }
            set {
                this.sodtField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Ngaysinh {
            get {
                return this.ngaysinhField;
            }
            set {
                this.ngaysinhField = value;
            }
        }
        
        /// <remarks/>
        public string Noisinh {
            get {
                return this.noisinhField;
            }
            set {
                this.noisinhField = value;
            }
        }
        
        /// <remarks/>
        public string Noithuongtru {
            get {
                return this.noithuongtruField;
            }
            set {
                this.noithuongtruField = value;
            }
        }
        
        /// <remarks/>
        public string Gioitinh {
            get {
                return this.gioitinhField;
            }
            set {
                this.gioitinhField = value;
            }
        }
        
        /// <remarks/>
        public string Dantoc {
            get {
                return this.dantocField;
            }
            set {
                this.dantocField = value;
            }
        }
        
        /// <remarks/>
        public string Tongiao {
            get {
                return this.tongiaoField;
            }
            set {
                this.tongiaoField = value;
            }
        }
        
        /// <remarks/>
        public string Socmnd {
            get {
                return this.socmndField;
            }
            set {
                this.socmndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhan[] LopHocPhans {
            get {
                return this.lopHocPhansField;
            }
            set {
                this.lopHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public LopSinhHoat[] LopSinhHoats {
            get {
                return this.lopSinhHoatsField;
            }
            set {
                this.lopSinhHoatsField = value;
            }
        }
        
        /// <remarks/>
        public NhatKy[] NhatKies {
            get {
                return this.nhatKiesField;
            }
            set {
                this.nhatKiesField = value;
            }
        }
        
        /// <remarks/>
        public TinTucDaoTao[] TinTucDaoTaos {
            get {
                return this.tinTucDaoTaosField;
            }
            set {
                this.tinTucDaoTaosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NhatKy {
        
        private int mankField;
        
        private string malhpField;
        
        private string macbgvField;
        
        private string tacvuField;
        
        private string lydoField;
        
        private System.Nullable<System.DateTime> thoigianField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private CanBoGiaoVien canBoGiaoVienField;
        
        private LopHocPhan lopHocPhanField;
        
        /// <remarks/>
        public int Mank {
            get {
                return this.mankField;
            }
            set {
                this.mankField = value;
            }
        }
        
        /// <remarks/>
        public string Malhp {
            get {
                return this.malhpField;
            }
            set {
                this.malhpField = value;
            }
        }
        
        /// <remarks/>
        public string Macbgv {
            get {
                return this.macbgvField;
            }
            set {
                this.macbgvField = value;
            }
        }
        
        /// <remarks/>
        public string Tacvu {
            get {
                return this.tacvuField;
            }
            set {
                this.tacvuField = value;
            }
        }
        
        /// <remarks/>
        public string Lydo {
            get {
                return this.lydoField;
            }
            set {
                this.lydoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Thoigian {
            get {
                return this.thoigianField;
            }
            set {
                this.thoigianField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public CanBoGiaoVien CanBoGiaoVien {
            get {
                return this.canBoGiaoVienField;
            }
            set {
                this.canBoGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhan LopHocPhan {
            get {
                return this.lopHocPhanField;
            }
            set {
                this.lopHocPhanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TinTucDaoTao {
        
        private int idField;
        
        private System.Nullable<int> matltField;
        
        private string macbgvField;
        
        private string tieudeField;
        
        private string tomtatField;
        
        private string noidungField;
        
        private string filedinhkemField;
        
        private System.Nullable<System.DateTime> thoigianField;
        
        private string hinhanhField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private CanBoGiaoVien canBoGiaoVienField;
        
        private TheLoaiTin theLoaiTinField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Matlt {
            get {
                return this.matltField;
            }
            set {
                this.matltField = value;
            }
        }
        
        /// <remarks/>
        public string Macbgv {
            get {
                return this.macbgvField;
            }
            set {
                this.macbgvField = value;
            }
        }
        
        /// <remarks/>
        public string Tieude {
            get {
                return this.tieudeField;
            }
            set {
                this.tieudeField = value;
            }
        }
        
        /// <remarks/>
        public string Tomtat {
            get {
                return this.tomtatField;
            }
            set {
                this.tomtatField = value;
            }
        }
        
        /// <remarks/>
        public string Noidung {
            get {
                return this.noidungField;
            }
            set {
                this.noidungField = value;
            }
        }
        
        /// <remarks/>
        public string Filedinhkem {
            get {
                return this.filedinhkemField;
            }
            set {
                this.filedinhkemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Thoigian {
            get {
                return this.thoigianField;
            }
            set {
                this.thoigianField = value;
            }
        }
        
        /// <remarks/>
        public string Hinhanh {
            get {
                return this.hinhanhField;
            }
            set {
                this.hinhanhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public CanBoGiaoVien CanBoGiaoVien {
            get {
                return this.canBoGiaoVienField;
            }
            set {
                this.canBoGiaoVienField = value;
            }
        }
        
        /// <remarks/>
        public TheLoaiTin TheLoaiTin {
            get {
                return this.theLoaiTinField;
            }
            set {
                this.theLoaiTinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TheLoaiTin {
        
        private int matltField;
        
        private string tentltField;
        
        private TinTucDaoTao[] tinTucDaoTaosField;
        
        /// <remarks/>
        public int Matlt {
            get {
                return this.matltField;
            }
            set {
                this.matltField = value;
            }
        }
        
        /// <remarks/>
        public string Tentlt {
            get {
                return this.tentltField;
            }
            set {
                this.tentltField = value;
            }
        }
        
        /// <remarks/>
        public TinTucDaoTao[] TinTucDaoTaos {
            get {
                return this.tinTucDaoTaosField;
            }
            set {
                this.tinTucDaoTaosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nganh {
        
        private string manganhField;
        
        private string tennganhField;
        
        private System.Nullable<int> sotcdcField;
        
        private System.Nullable<int> sotcbbField;
        
        private System.Nullable<int> sotctcField;
        
        private string moTaField;
        
        private string makhoaField;
        
        private LopSinhHoat[] lopSinhHoatsField;
        
        private NganhHocPhan[] nganhHocPhansField;
        
        private NganhHocPhanDieuKien[] nganhHocPhanDieuKiensField;
        
        private Khoa khoaField;
        
        /// <remarks/>
        public string Manganh {
            get {
                return this.manganhField;
            }
            set {
                this.manganhField = value;
            }
        }
        
        /// <remarks/>
        public string Tennganh {
            get {
                return this.tennganhField;
            }
            set {
                this.tennganhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotcdc {
            get {
                return this.sotcdcField;
            }
            set {
                this.sotcdcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotcbb {
            get {
                return this.sotcbbField;
            }
            set {
                this.sotcbbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotctc {
            get {
                return this.sotctcField;
            }
            set {
                this.sotctcField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        public string Makhoa {
            get {
                return this.makhoaField;
            }
            set {
                this.makhoaField = value;
            }
        }
        
        /// <remarks/>
        public LopSinhHoat[] LopSinhHoats {
            get {
                return this.lopSinhHoatsField;
            }
            set {
                this.lopSinhHoatsField = value;
            }
        }
        
        /// <remarks/>
        public NganhHocPhan[] NganhHocPhans {
            get {
                return this.nganhHocPhansField;
            }
            set {
                this.nganhHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public NganhHocPhanDieuKien[] NganhHocPhanDieuKiens {
            get {
                return this.nganhHocPhanDieuKiensField;
            }
            set {
                this.nganhHocPhanDieuKiensField = value;
            }
        }
        
        /// <remarks/>
        public Khoa Khoa {
            get {
                return this.khoaField;
            }
            set {
                this.khoaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NganhHocPhan {
        
        private int idField;
        
        private string manganhField;
        
        private string mahpField;
        
        private System.Nullable<bool> tuchonField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private Nganh nganhField;
        
        private HocPhan hocPhanField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Manganh {
            get {
                return this.manganhField;
            }
            set {
                this.manganhField = value;
            }
        }
        
        /// <remarks/>
        public string Mahp {
            get {
                return this.mahpField;
            }
            set {
                this.mahpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Tuchon {
            get {
                return this.tuchonField;
            }
            set {
                this.tuchonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public Nganh Nganh {
            get {
                return this.nganhField;
            }
            set {
                this.nganhField = value;
            }
        }
        
        /// <remarks/>
        public HocPhan HocPhan {
            get {
                return this.hocPhanField;
            }
            set {
                this.hocPhanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HocPhan {
        
        private string mahpField;
        
        private string tenhpField;
        
        private System.Nullable<int> sotcField;
        
        private System.Nullable<int> lythuyetField;
        
        private System.Nullable<int> thuchanhbtField;
        
        private System.Nullable<int> doanField;
        
        private string motaField;
        
        private string ghichuField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private LopHocPhan[] lopHocPhansField;
        
        private NganhHocPhan[] nganhHocPhansField;
        
        private NganhHocPhanDieuKien[] nganhHocPhanDieuKiensField;
        
        private TaiLieu[] taiLieusField;
        
        /// <remarks/>
        public string Mahp {
            get {
                return this.mahpField;
            }
            set {
                this.mahpField = value;
            }
        }
        
        /// <remarks/>
        public string Tenhp {
            get {
                return this.tenhpField;
            }
            set {
                this.tenhpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotc {
            get {
                return this.sotcField;
            }
            set {
                this.sotcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Lythuyet {
            get {
                return this.lythuyetField;
            }
            set {
                this.lythuyetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Thuchanhbt {
            get {
                return this.thuchanhbtField;
            }
            set {
                this.thuchanhbtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Doan {
            get {
                return this.doanField;
            }
            set {
                this.doanField = value;
            }
        }
        
        /// <remarks/>
        public string Mota {
            get {
                return this.motaField;
            }
            set {
                this.motaField = value;
            }
        }
        
        /// <remarks/>
        public string Ghichu {
            get {
                return this.ghichuField;
            }
            set {
                this.ghichuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhan[] LopHocPhans {
            get {
                return this.lopHocPhansField;
            }
            set {
                this.lopHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public NganhHocPhan[] NganhHocPhans {
            get {
                return this.nganhHocPhansField;
            }
            set {
                this.nganhHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public NganhHocPhanDieuKien[] NganhHocPhanDieuKiens {
            get {
                return this.nganhHocPhanDieuKiensField;
            }
            set {
                this.nganhHocPhanDieuKiensField = value;
            }
        }
        
        /// <remarks/>
        public TaiLieu[] TaiLieus {
            get {
                return this.taiLieusField;
            }
            set {
                this.taiLieusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NganhHocPhanDieuKien {
        
        private int idField;
        
        private string manganhField;
        
        private string mahpField;
        
        private string dieukienField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private Nganh nganhField;
        
        private HocPhan hocPhanField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Manganh {
            get {
                return this.manganhField;
            }
            set {
                this.manganhField = value;
            }
        }
        
        /// <remarks/>
        public string Mahp {
            get {
                return this.mahpField;
            }
            set {
                this.mahpField = value;
            }
        }
        
        /// <remarks/>
        public string Dieukien {
            get {
                return this.dieukienField;
            }
            set {
                this.dieukienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public Nganh Nganh {
            get {
                return this.nganhField;
            }
            set {
                this.nganhField = value;
            }
        }
        
        /// <remarks/>
        public HocPhan HocPhan {
            get {
                return this.hocPhanField;
            }
            set {
                this.hocPhanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaiLieu {
        
        private int idField;
        
        private string mahpField;
        
        private System.Nullable<int> sochuongField;
        
        private string tieudeField;
        
        private string noidungField;
        
        private string baitapField;
        
        private string docthemField;
        
        private System.Nullable<System.DateTime> ngaycnField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private HocPhan hocPhanField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Mahp {
            get {
                return this.mahpField;
            }
            set {
                this.mahpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sochuong {
            get {
                return this.sochuongField;
            }
            set {
                this.sochuongField = value;
            }
        }
        
        /// <remarks/>
        public string Tieude {
            get {
                return this.tieudeField;
            }
            set {
                this.tieudeField = value;
            }
        }
        
        /// <remarks/>
        public string Noidung {
            get {
                return this.noidungField;
            }
            set {
                this.noidungField = value;
            }
        }
        
        /// <remarks/>
        public string Baitap {
            get {
                return this.baitapField;
            }
            set {
                this.baitapField = value;
            }
        }
        
        /// <remarks/>
        public string Docthem {
            get {
                return this.docthemField;
            }
            set {
                this.docthemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Ngaycn {
            get {
                return this.ngaycnField;
            }
            set {
                this.ngaycnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public HocPhan HocPhan {
            get {
                return this.hocPhanField;
            }
            set {
                this.hocPhanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Khoa {
        
        private string makhoaField;
        
        private string tenkhoaField;
        
        private Nganh[] nganhsField;
        
        /// <remarks/>
        public string Makhoa {
            get {
                return this.makhoaField;
            }
            set {
                this.makhoaField = value;
            }
        }
        
        /// <remarks/>
        public string Tenkhoa {
            get {
                return this.tenkhoaField;
            }
            set {
                this.tenkhoaField = value;
            }
        }
        
        /// <remarks/>
        public Nganh[] Nganhs {
            get {
                return this.nganhsField;
            }
            set {
                this.nganhsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TheoDoiHocKy {
        
        private int idField;
        
        private string masvField;
        
        private string mahkField;
        
        private System.Nullable<int> tongtcField;
        
        private System.Nullable<double> dtbchkField;
        
        private System.Nullable<double> diemrlField;
        
        private System.Nullable<System.DateTime> thoigianField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private HocKy hocKyField;
        
        private SinhVien sinhVienField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        public string Mahk {
            get {
                return this.mahkField;
            }
            set {
                this.mahkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Tongtc {
            get {
                return this.tongtcField;
            }
            set {
                this.tongtcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dtbchk {
            get {
                return this.dtbchkField;
            }
            set {
                this.dtbchkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Diemrl {
            get {
                return this.diemrlField;
            }
            set {
                this.diemrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Thoigian {
            get {
                return this.thoigianField;
            }
            set {
                this.thoigianField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        public HocKy HocKy {
            get {
                return this.hocKyField;
            }
            set {
                this.hocKyField = value;
            }
        }
        
        /// <remarks/>
        public SinhVien SinhVien {
            get {
                return this.sinhVienField;
            }
            set {
                this.sinhVienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HocKy {
        
        private string mahkField;
        
        private string tenhkField;
        
        private LopHocPhan[] lopHocPhansField;
        
        private TheoDoiHocKy[] theoDoiHocKiesField;
        
        /// <remarks/>
        public string Mahk {
            get {
                return this.mahkField;
            }
            set {
                this.mahkField = value;
            }
        }
        
        /// <remarks/>
        public string Tenhk {
            get {
                return this.tenhkField;
            }
            set {
                this.tenhkField = value;
            }
        }
        
        /// <remarks/>
        public LopHocPhan[] LopHocPhans {
            get {
                return this.lopHocPhansField;
            }
            set {
                this.lopHocPhansField = value;
            }
        }
        
        /// <remarks/>
        public TheoDoiHocKy[] TheoDoiHocKies {
            get {
                return this.theoDoiHocKiesField;
            }
            set {
                this.theoDoiHocKiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChinhSach {
        
        private int macsField;
        
        private string tencsField;
        
        private SinhVien[] sinhViensField;
        
        /// <remarks/>
        public int Macs {
            get {
                return this.macsField;
            }
            set {
                this.macsField = value;
            }
        }
        
        /// <remarks/>
        public string Tencs {
            get {
                return this.tencsField;
            }
            set {
                this.tencsField = value;
            }
        }
        
        /// <remarks/>
        public SinhVien[] SinhViens {
            get {
                return this.sinhViensField;
            }
            set {
                this.sinhViensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getLopHocPhanDKByMasvCompletedEventHandler(object sender, getLopHocPhanDKByMasvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLopHocPhanDKByMasvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLopHocPhanDKByMasvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LopHocPhanDKWSI Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LopHocPhanDKWSI)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591