//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace ServiceClient.ThongTinSinhVienWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ThongTinSinhVienWSSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class ThongTinSinhVienWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ThongTinSinhVienWS() {
            this.Url = global::ServiceClient.Properties.Settings.Default.ServiceClient_ThongTinSinhVienWS_ThongTinSinhVienWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallServiceCompletedEventHandler CallServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CallService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ThongTinSinhVienWSI CallService(ThongTinSinhVienWSI wsi) {
            object[] results = this.Invoke("CallService", new object[] {
                        wsi});
            return ((ThongTinSinhVienWSI)(results[0]));
        }
        
        /// <remarks/>
        public void CallServiceAsync(ThongTinSinhVienWSI wsi) {
            this.CallServiceAsync(wsi, null);
        }
        
        /// <remarks/>
        public void CallServiceAsync(ThongTinSinhVienWSI wsi, object userState) {
            if ((this.CallServiceOperationCompleted == null)) {
                this.CallServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallServiceOperationCompleted);
            }
            this.InvokeAsync("CallService", new object[] {
                        wsi}, this.CallServiceOperationCompleted, userState);
        }
        
        private void OnCallServiceOperationCompleted(object arg) {
            if ((this.CallServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallServiceCompleted(this, new CallServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ThongTinSinhVienWSI {
        
        private SinhVien sinhVienField;
        
        private PhuHuynh phuHuynhField;
        
        private Khoa khoaField;
        
        private Nganh nganhField;
        
        private LopSinhHoat lopSinhHoatField;
        
        private ChinhSach chinhSachField;
        
        private TinTucSinhVien[] tinTucSinhViensField;
        
        private TheoDoiHocKy[] theoDoiHocKysField;
        
        private string isWsiErrorField;
        
        private object[] wsiErrorField;
        
        private string modeField;
        
        /// <remarks/>
        public SinhVien SinhVien {
            get {
                return this.sinhVienField;
            }
            set {
                this.sinhVienField = value;
            }
        }
        
        /// <remarks/>
        public PhuHuynh PhuHuynh {
            get {
                return this.phuHuynhField;
            }
            set {
                this.phuHuynhField = value;
            }
        }
        
        /// <remarks/>
        public Khoa Khoa {
            get {
                return this.khoaField;
            }
            set {
                this.khoaField = value;
            }
        }
        
        /// <remarks/>
        public Nganh Nganh {
            get {
                return this.nganhField;
            }
            set {
                this.nganhField = value;
            }
        }
        
        /// <remarks/>
        public LopSinhHoat LopSinhHoat {
            get {
                return this.lopSinhHoatField;
            }
            set {
                this.lopSinhHoatField = value;
            }
        }
        
        /// <remarks/>
        public ChinhSach ChinhSach {
            get {
                return this.chinhSachField;
            }
            set {
                this.chinhSachField = value;
            }
        }
        
        /// <remarks/>
        public TinTucSinhVien[] TinTucSinhViens {
            get {
                return this.tinTucSinhViensField;
            }
            set {
                this.tinTucSinhViensField = value;
            }
        }
        
        /// <remarks/>
        public TheoDoiHocKy[] TheoDoiHocKys {
            get {
                return this.theoDoiHocKysField;
            }
            set {
                this.theoDoiHocKysField = value;
            }
        }
        
        /// <remarks/>
        public string IsWsiError {
            get {
                return this.isWsiErrorField;
            }
            set {
                this.isWsiErrorField = value;
            }
        }
        
        /// <remarks/>
        public object[] WsiError {
            get {
                return this.wsiErrorField;
            }
            set {
                this.wsiErrorField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SinhVien {
        
        private string masvField;
        
        private int macsField;
        
        private int maphField;
        
        private string malshField;
        
        private string tensvField;
        
        private string sodtField;
        
        private string emailField;
        
        private System.Nullable<System.DateTime> ngaysinhField;
        
        private string noisinhField;
        
        private string noithuongtruField;
        
        private string gioitinhField;
        
        private string dantocField;
        
        private string tongiaoField;
        
        private string socmndField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        public int Macs {
            get {
                return this.macsField;
            }
            set {
                this.macsField = value;
            }
        }
        
        /// <remarks/>
        public int Maph {
            get {
                return this.maphField;
            }
            set {
                this.maphField = value;
            }
        }
        
        /// <remarks/>
        public string Malsh {
            get {
                return this.malshField;
            }
            set {
                this.malshField = value;
            }
        }
        
        /// <remarks/>
        public string Tensv {
            get {
                return this.tensvField;
            }
            set {
                this.tensvField = value;
            }
        }
        
        /// <remarks/>
        public string Sodt {
            get {
                return this.sodtField;
            }
            set {
                this.sodtField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Ngaysinh {
            get {
                return this.ngaysinhField;
            }
            set {
                this.ngaysinhField = value;
            }
        }
        
        /// <remarks/>
        public string Noisinh {
            get {
                return this.noisinhField;
            }
            set {
                this.noisinhField = value;
            }
        }
        
        /// <remarks/>
        public string Noithuongtru {
            get {
                return this.noithuongtruField;
            }
            set {
                this.noithuongtruField = value;
            }
        }
        
        /// <remarks/>
        public string Gioitinh {
            get {
                return this.gioitinhField;
            }
            set {
                this.gioitinhField = value;
            }
        }
        
        /// <remarks/>
        public string Dantoc {
            get {
                return this.dantocField;
            }
            set {
                this.dantocField = value;
            }
        }
        
        /// <remarks/>
        public string Tongiao {
            get {
                return this.tongiaoField;
            }
            set {
                this.tongiaoField = value;
            }
        }
        
        /// <remarks/>
        public string Socmnd {
            get {
                return this.socmndField;
            }
            set {
                this.socmndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TheoDoiHocKy {
        
        private int idField;
        
        private string masvField;
        
        private string mahkField;
        
        private System.Nullable<int> tongtcField;
        
        private System.Nullable<double> dtbchkField;
        
        private System.Nullable<double> diemrlField;
        
        private System.Nullable<System.DateTime> thoigianField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        public string Mahk {
            get {
                return this.mahkField;
            }
            set {
                this.mahkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Tongtc {
            get {
                return this.tongtcField;
            }
            set {
                this.tongtcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Dtbchk {
            get {
                return this.dtbchkField;
            }
            set {
                this.dtbchkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Diemrl {
            get {
                return this.diemrlField;
            }
            set {
                this.diemrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Thoigian {
            get {
                return this.thoigianField;
            }
            set {
                this.thoigianField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TinTucSinhVien {
        
        private int idField;
        
        private string masvField;
        
        private string tieudeField;
        
        private string tomtatField;
        
        private string noidungField;
        
        private string filedinhkemField;
        
        private System.Nullable<System.DateTime> thoigianField;
        
        private string hinhanhField;
        
        private System.Nullable<int> deleteUserIdField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Masv {
            get {
                return this.masvField;
            }
            set {
                this.masvField = value;
            }
        }
        
        /// <remarks/>
        public string Tieude {
            get {
                return this.tieudeField;
            }
            set {
                this.tieudeField = value;
            }
        }
        
        /// <remarks/>
        public string Tomtat {
            get {
                return this.tomtatField;
            }
            set {
                this.tomtatField = value;
            }
        }
        
        /// <remarks/>
        public string Noidung {
            get {
                return this.noidungField;
            }
            set {
                this.noidungField = value;
            }
        }
        
        /// <remarks/>
        public string Filedinhkem {
            get {
                return this.filedinhkemField;
            }
            set {
                this.filedinhkemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Thoigian {
            get {
                return this.thoigianField;
            }
            set {
                this.thoigianField = value;
            }
        }
        
        /// <remarks/>
        public string Hinhanh {
            get {
                return this.hinhanhField;
            }
            set {
                this.hinhanhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChinhSach {
        
        private int macsField;
        
        private string tencsField;
        
        /// <remarks/>
        public int Macs {
            get {
                return this.macsField;
            }
            set {
                this.macsField = value;
            }
        }
        
        /// <remarks/>
        public string Tencs {
            get {
                return this.tencsField;
            }
            set {
                this.tencsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LopSinhHoat {
        
        private string malshField;
        
        private string manganhField;
        
        private string macbgvField;
        
        private string tenlshField;
        
        private int sisoField;
        
        private int khoaField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        /// <remarks/>
        public string Malsh {
            get {
                return this.malshField;
            }
            set {
                this.malshField = value;
            }
        }
        
        /// <remarks/>
        public string Manganh {
            get {
                return this.manganhField;
            }
            set {
                this.manganhField = value;
            }
        }
        
        /// <remarks/>
        public string Macbgv {
            get {
                return this.macbgvField;
            }
            set {
                this.macbgvField = value;
            }
        }
        
        /// <remarks/>
        public string Tenlsh {
            get {
                return this.tenlshField;
            }
            set {
                this.tenlshField = value;
            }
        }
        
        /// <remarks/>
        public int Siso {
            get {
                return this.sisoField;
            }
            set {
                this.sisoField = value;
            }
        }
        
        /// <remarks/>
        public int Khoa {
            get {
                return this.khoaField;
            }
            set {
                this.khoaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nganh {
        
        private string manganhField;
        
        private string tennganhField;
        
        private System.Nullable<int> sotcdcField;
        
        private System.Nullable<int> sotcbbField;
        
        private System.Nullable<int> sotctcField;
        
        private string moTaField;
        
        private string makhoaField;
        
        /// <remarks/>
        public string Manganh {
            get {
                return this.manganhField;
            }
            set {
                this.manganhField = value;
            }
        }
        
        /// <remarks/>
        public string Tennganh {
            get {
                return this.tennganhField;
            }
            set {
                this.tennganhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotcdc {
            get {
                return this.sotcdcField;
            }
            set {
                this.sotcdcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotcbb {
            get {
                return this.sotcbbField;
            }
            set {
                this.sotcbbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Sotctc {
            get {
                return this.sotctcField;
            }
            set {
                this.sotctcField = value;
            }
        }
        
        /// <remarks/>
        public string MoTa {
            get {
                return this.moTaField;
            }
            set {
                this.moTaField = value;
            }
        }
        
        /// <remarks/>
        public string Makhoa {
            get {
                return this.makhoaField;
            }
            set {
                this.makhoaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Khoa {
        
        private string makhoaField;
        
        private string tenkhoaField;
        
        /// <remarks/>
        public string Makhoa {
            get {
                return this.makhoaField;
            }
            set {
                this.makhoaField = value;
            }
        }
        
        /// <remarks/>
        public string Tenkhoa {
            get {
                return this.tenkhoaField;
            }
            set {
                this.tenkhoaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhuHuynh {
        
        private int maphField;
        
        private string hotenchaField;
        
        private string nghenghiepchaField;
        
        private string hotenmeField;
        
        private string nghenghiepmeField;
        
        private string diachiField;
        
        private string sodienthoaiField;
        
        private string emailField;
        
        private System.Nullable<System.DateTime> deleteDateField;
        
        private System.Nullable<int> deleteUserIdField;
        
        /// <remarks/>
        public int Maph {
            get {
                return this.maphField;
            }
            set {
                this.maphField = value;
            }
        }
        
        /// <remarks/>
        public string Hotencha {
            get {
                return this.hotenchaField;
            }
            set {
                this.hotenchaField = value;
            }
        }
        
        /// <remarks/>
        public string Nghenghiepcha {
            get {
                return this.nghenghiepchaField;
            }
            set {
                this.nghenghiepchaField = value;
            }
        }
        
        /// <remarks/>
        public string Hotenme {
            get {
                return this.hotenmeField;
            }
            set {
                this.hotenmeField = value;
            }
        }
        
        /// <remarks/>
        public string Nghenghiepme {
            get {
                return this.nghenghiepmeField;
            }
            set {
                this.nghenghiepmeField = value;
            }
        }
        
        /// <remarks/>
        public string Diachi {
            get {
                return this.diachiField;
            }
            set {
                this.diachiField = value;
            }
        }
        
        /// <remarks/>
        public string Sodienthoai {
            get {
                return this.sodienthoaiField;
            }
            set {
                this.sodienthoaiField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeleteDate {
            get {
                return this.deleteDateField;
            }
            set {
                this.deleteDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeleteUserId {
            get {
                return this.deleteUserIdField;
            }
            set {
                this.deleteUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CallServiceCompletedEventHandler(object sender, CallServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ThongTinSinhVienWSI Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ThongTinSinhVienWSI)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591